# Generated by Django 5.2.4 on 2025-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calculationhistory_millionaire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationhistory',
            name='millionaire_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='principle',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
